---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-nacos-yunweizhan-com-cn-v1alpha1-nacoscluster
  failurePolicy: Fail
  name: mnacoscluster.kb.io
  rules:
  - apiGroups:
    - nacos.yunweizhan.com.cn
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nacosclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-nacos-yunweizhan-com-cn-v1alpha1-nacosstandalone
  failurePolicy: Fail
  name: mnacosstandalone.kb.io
  rules:
  - apiGroups:
    - nacos.yunweizhan.com.cn
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nacosstandalones
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nacos-yunweizhan-com-cn-v1alpha1-nacoscluster
  failurePolicy: Fail
  name: vnacoscluster.kb.io
  rules:
  - apiGroups:
    - nacos.yunweizhan.com.cn
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nacosclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nacos-yunweizhan-com-cn-v1alpha1-nacosstandalone
  failurePolicy: Fail
  name: vnacosstandalone.kb.io
  rules:
  - apiGroups:
    - nacos.yunweizhan.com.cn
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nacosstandalones
  sideEffects: None
