# permissions for end users to edit nacosclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nacoscluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nacos-operator
    app.kubernetes.io/part-of: nacos-operator
    app.kubernetes.io/managed-by: kustomize
  name: nacoscluster-editor-role
rules:
- apiGroups:
  - nacos.yunweizhan.com.cn
  resources:
  - nacosclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nacos.yunweizhan.com.cn
  resources:
  - nacosclusters/status
  verbs:
  - get
