apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: Database
    containerImage: quay.io/yunye/nacos/nacos-operator
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.arm64: supported
    operatorframework.io/arch.ppc64le: supported
    operatorframework.io/arch.s390x: supported
    operatorframework.io/infrastructure-features: '["disconnected"]'
    operatorframework.io/os.linux: supported
    operatorframework.io/suggested-namespace: nacos-operator-system
    repository: https://github.com/YunWZ/nacos-operator
    support: Yun Ye
  name: nacos-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: NacosCluster is the Schema for the nacosclusters API
      displayName: Nacos Cluster
      kind: NacosCluster
      name: nacosclusters.nacos.yunweizhan.com.cn
      version: v1alpha1
    - description: NacosStandalone is the Schema for the nacosstandalones API
      displayName: Nacos Standalone
      kind: NacosStandalone
      name: nacosstandalones.nacos.yunweizhan.com.cn
      version: v1alpha1
  description: an operator for deploying nacos (Standalone and Cluster mode)
  displayName: nacos-operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAMwAAAAoCAMAAACFKeVUAAAANlBMVEVHcEz///////////////////////////////////////////////////////////////////+GUsxbAAAAEXRSTlMA+1oFDSpssPLjwNWfGTyFSq4AOP8AAAVySURBVGjetVnXguQoDDQ5GbD//2fPCRAgsHtvl5l+mDENFKVQkpdlWXzwCzI2eo2APVvE8YAv08HEJh0x8XXiObjY4jVZ8NmCtB2e1cdSetcrAsfu11iRZYMlZCdOTpCE42z7M4yifgp7W4/J5J5vVspRJNHpvRu0vpJ7T8t+AEP1vS9Z2eB41DabmjiEw6gjpJrsYgfHrwiSDgxN5/oOhpa1VtwGbb8rMQMeAzJ5d7SZZHZ8bNW0mDbr9lKD8wq4MHZCiV8iURg5keCnXCE5QQ9mNcysea/tIzOqMp/ugCwO9iXEic7v19Epd1tW9iNeWmbKaqbZyt5PWr8ItYHHFss63Hjv0HA1nrw73134GzMRbMW/MNOs3FIT99moL2yK5eDmOY8gX8FI8EQxzGdqZryexxN48lVuIdBoB2gqLG6l12S3d+Elu5Ve5ZVcZPn4IRgSX5lhab5Ju1r4FFi3k8/FMhYUhgZgIY6Wybb1iPQPK87n7Lzc9FnYEEx9zajPsIQhhnQQwTAbrKLRQgtIE3oskdXRMFFhzkW4uf/U4lVH1GB0eGEmPPuQUGCBLE1GgR7E89uYIRa6jLKKBIbt2I9gQAhJPqNQ9z8UQzJlw3tiYp9IXRVyuR1jOfNKOg4vYOy7wouDEIIzk33iuDKhW9vMwUFhssBBLIUXTRGFI4HX/Dkz4PCPz1QHkw8b2oPsqRppNLDuC03HC4bldE2ST8NdsuyvYIztFArGjIWIUxjOZ1+niu1Ec/P+iqWsfdKRLs1s7BsYl2066xrEZ0QVM9kTZrKHWFRjgK/fIc5b8oblCGEpVkLjcWp9RpRYlZTAFKdLqaBnJsuux3wjcFPgUGZejEHf34Z1gcozGMjT5Pm5qwoxAsOzxafD9T6TritRkSPxfSZP0sXMBuRlYjcRRJeRRNKR4T7D4HeuVNAzk53EN3alKmxqjqWcZZsUnxJ4MHcD4borPmAG5u+I+oxqNVyNLoGZJoSXoNxFWVklqW7UchIwA62Z5msvYNJhS5aDaafY9jy7fUPDYpXEvB2hkSNmDtFBiq7pfAZL+QR8nT+aSvO/gEbVkZHJATnaI8zwWkcQ41szQ8RYlmr7mdCYfYlR3m5f0STOS/7ldHVak/uH4NRAM6vqEdua2baX0I9n0dekSXRgLyITSZoAokhjyxUy7CvJxnRi14Zo6+GqKyUh250kqLzAnxJFf+OG2fm9AO0Es9qjtsq/2oJbtSqSsqrwJECsm3eh+Q2N3F/ExDEe+QYNRT4uwpFEAJkpJaYf1QTgIuS4BPiCJrkumYmJtILomWF4Xyzfcnb/hvhUcF4hoEgiOcKSAucMTV2cvYJhQ5+pjgTAlBKzFes7aImCtPtT2VxPLiF1QkySBVpMfKZpsSQw60h4SVivA03oSuckKNJhqdHY3CyvGhr0Q1VpJtGsC2mqz/W1AVUFJ626RzJcrSaQFmatpnC3mvLk3P8OWzdK/0otc2YOAU4a9UOxhPvYLoEhO9ZKsGsCst+bgEcyS9KfXKNamd6tlKu8oWgNAkKagnGfIEG3Tqaz9mzXAf7YnrWzWfx67UB2twEzY4PW0MWMmMT9LNDv6oKNe+FY43zMS3kpNgND8zumIxLQQXUYYKelLTEHrsj/0SuNCZgI0oNKYDRvj5kaMed9tyXmLASM3h/9j5dNYzC3MTyGbvBoVi6cXGF8KrqQntMvrwFZr+5dM3kEJkF+EsKWmfFI5XpIbiXu054hhBA1krjXY4iVhRW+oJUfXtCWt7kcV2FNIVNy051mj0Duj6B9xPGAOAPj3j89ZCHC+etH77TDPaGO74JKs+sjf/gvr85pNOScjCR9KmWU9UdWizJhzRGa/gOM3O3QHVCwHwAAAABJRU5ErkJggg==
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - nacos
  - microservice
  links:
  - name: Nacos Project
    url: https://nacos.io/
  - name: Nacos Source Code
    url: https://github.com/alibaba/nacos/
  - name: Operator Source Code
    url: https://github.com/YunWZ/nacos-operator/
  maintainers:
  - email: verdgun@gmail.com
    name: Yun Ye
  maturity: alpha
  minKubeVersion: 1.27.0
  provider:
    name: yunye
    url: https://github.com/YunWZ/nacos-operator
  version: 0.0.0
  webhookdefinitions:
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: nacos-operator-controller-manager
    failurePolicy: Fail
    generateName: vnacoscluster.kb.io
    rules:
    - apiGroups:
      - nacos.yunweizhan.com.cn
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - nacosclusters
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-nacos-yunweizhan-com-cn-v1alpha1-nacoscluster
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: nacos-operator-controller-manager
    failurePolicy: Fail
    generateName: vnacosstandalone.kb.io
    rules:
    - apiGroups:
      - nacos.yunweizhan.com.cn
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - nacosstandalones
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-nacos-yunweizhan-com-cn-v1alpha1-nacosstandalone
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: nacos-operator-controller-manager
    failurePolicy: Fail
    generateName: mnacoscluster.kb.io
    rules:
    - apiGroups:
      - nacos.yunweizhan.com.cn
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - nacosclusters
    sideEffects: None
    targetPort: 9443
    type: MutatingAdmissionWebhook
    webhookPath: /mutate-nacos-yunweizhan-com-cn-v1alpha1-nacoscluster
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: nacos-operator-controller-manager
    failurePolicy: Fail
    generateName: mnacosstandalone.kb.io
    rules:
    - apiGroups:
      - nacos.yunweizhan.com.cn
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - nacosstandalones
    sideEffects: None
    targetPort: 9443
    type: MutatingAdmissionWebhook
    webhookPath: /mutate-nacos-yunweizhan-com-cn-v1alpha1-nacosstandalone
