apiVersion: nacos.yunweizhan.com.cn/v1alpha1
kind: NacosCluster
metadata:
  labels:
    app.kubernetes.io/name: nacoscluster
    app.kubernetes.io/instance: nacoscluster-sample
    app.kubernetes.io/part-of: nacos-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: nacos-operator
  name: nacoscluster-sample
spec:
  # TODO(user): Add fields here
